# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudping < Formula
  desc "cloudping identifies the cloud provider regions geographically closest and returns them in order of lowest to highest latency."
  homepage "https://github.com/estahn/cloudping"
  version "1.2.148"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/estahn/cloudping/releases/download/v1.2.148/cloudping_1.2.148_darwin_amd64.tar.gz"
      sha256 "55d96aefa6dce5f4474f49005a4d557929ad4cc7c9e7113d0ba011a347e8afdf"

      def install
        bin.install "cloudping"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/estahn/cloudping/releases/download/v1.2.148/cloudping_1.2.148_darwin_arm64.tar.gz"
      sha256 "3630be6e56b07873d83580c6861c3a722013f48b1badefc5cf6868385d9b02d6"

      def install
        bin.install "cloudping"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/estahn/cloudping/releases/download/v1.2.148/cloudping_1.2.148_linux_amd64.tar.gz"
      sha256 "4b3ea6e9e3e6fc64642f6b48609fb388817e6f4e81f203c744d925e1b5a86909"

      def install
        bin.install "cloudping"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/estahn/cloudping/releases/download/v1.2.148/cloudping_1.2.148_linux_armv6.tar.gz"
      sha256 "f05007f9efa898a1894f6e8f43d769f1cc0c583c94885c448d3d54b1c528ca34"

      def install
        bin.install "cloudping"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/estahn/cloudping/releases/download/v1.2.148/cloudping_1.2.148_linux_arm64.tar.gz"
      sha256 "9a888ab3bc7fcbc3b3a85147eecd73b22cd62b416b987cf34831e453e55de264"

      def install
        bin.install "cloudping"
      end
    end
  end
end
