# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudping < Formula
  desc "cloudping identifies the cloud provider regions geographically closest and returns them in order of lowest to highest latency."
  homepage "https://github.com/estahn/cloudping"
  version "1.2.158"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/estahn/cloudping/releases/download/v1.2.158/cloudping_1.2.158_darwin_arm64.tar.gz"
      sha256 "e8634479a36caa57c81b7da2858454293214bf159e9a0e97ef1074fccac4f509"

      def install
        bin.install "cloudping"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/estahn/cloudping/releases/download/v1.2.158/cloudping_1.2.158_darwin_amd64.tar.gz"
      sha256 "b32717334b49cfd741a3d07609b5d729c8952f9a3517f8d4688234dc16c08470"

      def install
        bin.install "cloudping"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/estahn/cloudping/releases/download/v1.2.158/cloudping_1.2.158_linux_amd64.tar.gz"
      sha256 "648546fdad44157739f9246f3ae3d42d5f097a08990992fbcd20fc130bc0b9fa"

      def install
        bin.install "cloudping"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/estahn/cloudping/releases/download/v1.2.158/cloudping_1.2.158_linux_arm64.tar.gz"
      sha256 "53362bfb67321374ba896bd998ae004893285b0cd54aed0708ed127b4f813c80"

      def install
        bin.install "cloudping"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/estahn/cloudping/releases/download/v1.2.158/cloudping_1.2.158_linux_armv6.tar.gz"
      sha256 "f3ea6401c0445cd9ed74812271494fab806f9a2295d0492feba120c4bba9aa82"

      def install
        bin.install "cloudping"
      end
    end
  end
end
